all: build

build:
	go build -o bin/punchserver ./punchserver
	go build -o bin/punchclient ./punchclient
	go build -o bin/punchconfig ./punchconfig
	go build -o bin/echoserver ./echoserver
	go build -o bin/echoclient ./echoclient

clean:
	rm -rf bin
